name: test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, master]

jobs:

  lint:
    name: Lint the code
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: super-linter/super-linter@v6.8.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew clean check -Dtest.profile=integration
        env:
          BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
          BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}

          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          TEST_DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}

          TEST_JWT_ISSUER: ${{ secrets.TEST_JWT_ISSUER }}
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_PUBLIC_KEY:  ${{ secrets.TEST_PUBLIC_KEY }}

          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
