name: test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, master]

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew clean check